extends:
  - "@epilot/eslint-config"
ignorePatterns:
  - node_modules
  - dist
rules:
  "spaced-comment":
    - error
    - always
    - line:
        markers: ["/"]
        exceptions: ["-", "+"]
      block:
        markers: ["!"]
        exceptions: ["*"]
        balanced: true
  "prettier/prettier":
    - error
    - printWidth: 120 # https://hackernoon.com/does-column-width-of-80-make-sense-in-2018-50c161fbdcf6
      trailingComma: all # better diffs, obviously
      bracketSpacing: true # more space = pretty
      semi: true # https://github.com/standard/semistandard
      useTabs: false
      tabWidth: 2
      singleQuote: true
      quoteProps: as-needed
      proseWrap: never
