// Auto-generated by scripts/generate.ts — do not edit
import { defineCommand } from 'citty';
import { callApi } from '../../lib/call.js';

export default defineCommand({
  meta: { name: 'journey', description: "Journey API" },
  args: {
    operation: { type: 'positional', description: 'operationId to call', required: false },
    param: { type: 'string', alias: 'p', description: 'Parameter key=value' },
    data: { type: 'string', alias: 'd', description: 'Request body JSON' },
    header: { type: 'string', alias: 'H', description: 'Custom header' },
    include: { type: 'boolean', alias: 'i', description: 'Include response headers' },
    definition: { type: 'string', description: 'Override OpenAPI spec file/URL' },
    server: { type: 'string', alias: 's', description: 'Override server base URL' },
    profile: { type: 'string', description: 'Use a named profile' },
  },
  run: ({ args, rawArgs }) => {
    // Extract additional positional args (after operationId)
    const positionalArgs: string[] = [];
    if (args.operation && rawArgs) {
      const opIdx = rawArgs.indexOf(args.operation);
      if (opIdx >= 0) {
        for (let i = opIdx + 1; i < rawArgs.length; i++) {
          const arg = rawArgs[i];
          if (arg.startsWith('-')) break;
          positionalArgs.push(arg);
        }
      }
    }

    return callApi('journey', {
      ...args,
      _args: positionalArgs,
    });
  },
});
