import { UsernamePasswordAuthParams } from '@epilot/auth';
import { default as addressSuggestionsClient } from './address-suggestions-client';
import { default as automationClient } from './automation-client';
import { default as discussionClient } from './discussion-client';
import { default as emailSettingsClient } from './email-settings-client';
import { default as emailTemplateClient } from './email-template-client';
import { default as entityClient } from './entity-client';
import { default as fileClient } from './file-client';
import { default as messageClient } from './message-client';
import { default as notificationClient } from './notification-client';
import { default as organizationClient } from './organization-client';
import { default as partnerClient } from './partner-directory-client';
import { default as permissionsClient } from './permissions-client';
import { default as pricingClient } from './pricing-client';
import { default as submissionClient } from './submission-client';
import { default as templateVariablesClient } from './template-variables-client';
import { default as terraformBlueprintsClient } from './tf-blueprints-client';
import { default as userClient } from './user-client';
import { default as workflowClient } from './workflow-client';
export declare class EpilotClient {
    get entity(): import("@epilot/entity-client/dist/openapi").Client;
    get pricing(): import("@epilot/pricing-client/dist/openapi").Client;
    get user(): import("@epilot/user-client/dist/openapi").Client;
    get file(): import("@epilot/file-client/dist/openapi").Client;
    get organization(): import("@epilot/organization-client/dist/openapi").Client;
    get submission(): import("@epilot/organization-client/dist/openapi").Client;
    get workflow(): import("@epilot/workflow-client/dist/openapi").Client;
    get permissions(): import("@epilot/permissions-client/dist/openapi").Client;
    get automation(): import("@epilot/automation-client/dist/openapi").Client;
    get message(): import("@epilot/message-client/dist/openapi").Client;
    get emailSettings(): import("@epilot/email-settings-client/dist/openapi").Client;
    get discussion(): import("@epilot/discussion-client/dist/openapi").Client;
    get notification(): import("@epilot/notification-client/dist/openapi").Client;
    get emailTemplate(): import("@epilot/email-template-client/dist/openapi").Client;
    get templateVariables(): import("@epilot/template-variables-client/dist/openapi").Client;
    get partner(): import("@epilot/partner-directory-client/dist/openapi").Client;
    get addressSuggestions(): import("@epilot/address-suggestions-client/dist/openapi").Client;
    get terraformBlueprints(): import("@epilot/tf-blueprints-client/dist/openapi").Client;
    authorize(token: string): this;
    login(credentials: UsernamePasswordAuthParams): Promise<this>;
}
export default EpilotClient;
export { entityClient };
export { pricingClient };
export { userClient };
export { fileClient };
export { organizationClient };
export { submissionClient };
export { workflowClient };
export { permissionsClient };
export { automationClient };
export { messageClient };
export { emailSettingsClient };
export { discussionClient };
export { notificationClient };
export { emailTemplateClient };
export { templateVariablesClient };
export { partnerClient };
export { addressSuggestionsClient };
export { terraformBlueprintsClient };
