import { defineCommand } from 'citty';

export const main = defineCommand({
  meta: {
    name: 'epilot',
    version: '0.1.12',
    description: 'CLI for epilot APIs',
  },
  args: {
    token: { type: 'string', alias: 't', description: 'Bearer token' },
    profile: { type: 'string', description: 'Use a named profile (or EPILOT_PROFILE env)' },
    server: { type: 'string', alias: 's', description: 'Override server base URL' },
    json: { type: 'boolean', description: 'Output raw JSON' },
    verbose: { type: 'boolean', alias: 'v', description: 'Verbose output' },
    guided: { type: 'boolean', description: 'Prompt for all parameters interactively' },
    interactive: { type: 'boolean', default: true, description: 'Interactive mode' },
    jsonata: { type: 'string', description: 'JSONata expression' },
  },
  subCommands: {
    auth: () => import('./commands/auth.js').then((m) => m.default),
    profile: () => import('./commands/profile.js').then((m) => m.default),
    completion: () => import('./commands/completion.js').then((m) => m.default),
    upgrade: () => import('./commands/upgrade.js').then((m) => m.default),
    'access-token': () => import('./commands/apis/access-token.js').then((m) => m.default),
    address: () => import('./commands/apis/address.js').then((m) => m.default),
    'address-suggestions': () => import('./commands/apis/address-suggestions.js').then((m) => m.default),
    'ai-agents': () => import('./commands/apis/ai-agents.js').then((m) => m.default),
    app: () => import('./commands/app/index.js').then((m) => m.default),
    'audit-logs': () => import('./commands/apis/audit-logs.js').then((m) => m.default),
    automation: () => import('./commands/apis/automation.js').then((m) => m.default),
    billing: () => import('./commands/apis/billing.js').then((m) => m.default),
    'blueprint-manifest': () => import('./commands/apis/blueprint-manifest.js').then((m) => m.default),
    consent: () => import('./commands/apis/consent.js').then((m) => m.default),
    'customer-portal': () => import('./commands/apis/customer-portal.js').then((m) => m.default),
    dashboard: () => import('./commands/apis/dashboard.js').then((m) => m.default),
    'data-governance': () => import('./commands/apis/data-governance.js').then((m) => m.default),
    deduplication: () => import('./commands/apis/deduplication.js').then((m) => m.default),
    design: () => import('./commands/apis/design.js').then((m) => m.default),
    document: () => import('./commands/apis/document.js').then((m) => m.default),
    'email-settings': () => import('./commands/apis/email-settings.js').then((m) => m.default),
    'email-template': () => import('./commands/apis/email-template.js').then((m) => m.default),
    entity: () => import('./commands/apis/entity.js').then((m) => m.default),
    'entity-mapping': () => import('./commands/apis/entity-mapping.js').then((m) => m.default),
    environments: () => import('./commands/apis/environments.js').then((m) => m.default),
    'event-catalog': () => import('./commands/apis/event-catalog.js').then((m) => m.default),
    file: () => import('./commands/apis/file.js').then((m) => m.default),
    iban: () => import('./commands/apis/iban.js').then((m) => m.default),
    'integration-toolkit': () => import('./commands/apis/integration-toolkit.js').then((m) => m.default),
    journey: () => import('./commands/apis/journey.js').then((m) => m.default),
    kanban: () => import('./commands/apis/kanban.js').then((m) => m.default),
    message: () => import('./commands/apis/message.js').then((m) => m.default),
    metering: () => import('./commands/apis/metering.js').then((m) => m.default),
    notes: () => import('./commands/apis/notes.js').then((m) => m.default),
    notification: () => import('./commands/apis/notification.js').then((m) => m.default),
    organization: () => import('./commands/apis/organization.js').then((m) => m.default),
    'partner-directory': () => import('./commands/apis/partner-directory.js').then((m) => m.default),
    permissions: () => import('./commands/apis/permissions.js').then((m) => m.default),
    pricing: () => import('./commands/apis/pricing.js').then((m) => m.default),
    'pricing-tier': () => import('./commands/apis/pricing-tier.js').then((m) => m.default),
    purpose: () => import('./commands/apis/purpose.js').then((m) => m.default),
    sandbox: () => import('./commands/apis/sandbox.js').then((m) => m.default),
    sharing: () => import('./commands/apis/sharing.js').then((m) => m.default),
    submission: () => import('./commands/apis/submission.js').then((m) => m.default),
    targeting: () => import('./commands/apis/targeting.js').then((m) => m.default),
    'template-variables': () => import('./commands/apis/template-variables.js').then((m) => m.default),
    user: () => import('./commands/apis/user.js').then((m) => m.default),
    'validation-rules': () => import('./commands/apis/validation-rules.js').then((m) => m.default),
    webhooks: () => import('./commands/apis/webhooks.js').then((m) => m.default),
    workflow: () => import('./commands/apis/workflow.js').then((m) => m.default),
    'workflow-definition': () => import('./commands/apis/workflow-definition.js').then((m) => m.default),
  },
});
