#!/usr/bin/env tsx

/**
 * Generates CLI files from existing API clients:
 * - Copies full openapi.json specs to definitions/
 * - Generates src/generated/api-list.ts
 * - Generates src/commands/apis/*.ts (one per API)
 * - Updates src/index.ts with subCommands map
 */

import { readdirSync, existsSync, copyFileSync, writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ROOT = resolve(__dirname, '..', '..', '..');
const CLIENTS_DIR = resolve(ROOT, 'clients');
const CLI_DIR = resolve(ROOT, 'packages', 'cli');
const DEFS_DIR = resolve(CLI_DIR, 'definitions');
const APIS_CMD_DIR = resolve(CLI_DIR, 'src', 'commands', 'apis');
const GENERATED_DIR = resolve(CLI_DIR, 'src', 'generated');

const toCamelCase = (name: string): string => {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
};

type ClientInfo = {
  dirName: string;
  apiName: string;
  kebabName: string;
  hasDefinition: boolean;
  title: string;
  description: string;
  serverUrl: string;
  operations: OperationSummary[];
};

type OperationSummary = {
  operationId: string;
  method: string;
  path: string;
  summary: string;
};

const discoverClients = (): ClientInfo[] => {
  const dirs = readdirSync(CLIENTS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name.endsWith('-client'))
    .map((d) => d.name);

  return dirs.map((dirName) => {
    const baseName = dirName.replace(/-client$/, '');
    const apiName = toCamelCase(baseName);
    const clientDir = resolve(CLIENTS_DIR, dirName, 'src');
    const fullSpecPath = resolve(clientDir, 'openapi.json');
    const runtimeSpecPath = resolve(clientDir, 'openapi-runtime.json');
    const hasDefinition = existsSync(fullSpecPath) || existsSync(runtimeSpecPath);

    let title = apiName;
    let description = '';
    let serverUrl = '';
    let operations: OperationSummary[] = [];

    const specPath = existsSync(fullSpecPath) ? fullSpecPath : runtimeSpecPath;
    if (hasDefinition && existsSync(specPath)) {
      try {
        const raw = JSON.parse(readFileSync(specPath, 'utf-8'));
        title = raw.info?.title || apiName;
        description = (raw.info?.description || '').substring(0, 120);
        serverUrl = raw.servers?.[0]?.url || '';

        // Extract operations
        for (const [path, methods] of Object.entries((raw.paths || {}) as Record<string, Record<string, unknown>>)) {
          for (const method of ['get', 'post', 'put', 'patch', 'delete', 'head', 'options']) {
            const op = methods[method] as Record<string, unknown> | undefined;
            if (!op?.operationId) continue;
            operations.push({
              operationId: op.operationId as string,
              method: method.toUpperCase(),
              path,
              summary: ((op.summary || op.description || '') as string).substring(0, 80),
            });
          }
        }
      } catch {
        // Ignore spec parse errors
      }
    }

    return { dirName, apiName, kebabName: baseName, hasDefinition, title, description, serverUrl, operations };
  });
};

const copyDefinitions = (clients: ClientInfo[]) => {
  mkdirSync(DEFS_DIR, { recursive: true });
  for (const client of clients) {
    if (!client.hasDefinition) continue;
    const fullSrc = resolve(CLIENTS_DIR, client.dirName, 'src/openapi.json');
    const runtimeSrc = resolve(CLIENTS_DIR, client.dirName, 'src/openapi-runtime.json');
    const src = existsSync(fullSrc) ? fullSrc : runtimeSrc;
    const dest = resolve(DEFS_DIR, `${client.kebabName}.json`);
    copyFileSync(src, dest);
  }
};

const generateApiList = (clients: ClientInfo[]): string => {
  const entries = clients.filter((c) => c.hasDefinition).map((c) => {
    return `  { apiName: '${c.apiName}', kebabName: '${c.kebabName}', title: ${JSON.stringify(c.title)}, serverUrl: '${c.serverUrl}', operationCount: ${c.operations.length} }`;
  });

  return `// Auto-generated by scripts/generate.ts — do not edit
export type ApiInfo = {
  apiName: string;
  kebabName: string;
  title: string;
  serverUrl: string;
  operationCount: number;
};

export const API_LIST: ApiInfo[] = [
${entries.join(',\n')},
];

export const API_NAMES = API_LIST.map((a) => a.apiName);
`;
};

const generateApiCommand = (client: ClientInfo): string => {
  return `// Auto-generated by scripts/generate.ts — do not edit
import { defineCommand } from 'citty';
import { callApi } from '../../lib/call.js';

export default defineCommand({
  meta: { name: '${client.kebabName}', description: ${JSON.stringify(client.title)} },
  args: {
    operation: { type: 'positional', description: 'operationId to call', required: false },
    param: { type: 'string', alias: 'p', description: 'Parameter key=value' },
    data: { type: 'string', alias: 'd', description: 'Request body JSON' },
    header: { type: 'string', alias: 'H', description: 'Custom header' },
    include: { type: 'boolean', alias: 'i', description: 'Include response headers' },
    definition: { type: 'string', description: 'Override OpenAPI spec file/URL' },
    server: { type: 'string', alias: 's', description: 'Override server base URL' },
    profile: { type: 'string', description: 'Use a named profile' },
  },
  run: ({ args, rawArgs }) => {
    // Extract additional positional args (after operationId)
    const positionalArgs: string[] = [];
    if (args.operation && rawArgs) {
      const opIdx = rawArgs.indexOf(args.operation);
      if (opIdx >= 0) {
        for (let i = opIdx + 1; i < rawArgs.length; i++) {
          const arg = rawArgs[i];
          if (arg.startsWith('-')) break;
          positionalArgs.push(arg);
        }
      }
    }

    return callApi('${client.kebabName}', {
      ...args,
      _args: positionalArgs,
    });
  },
});
`;
};

const generateIndexFile = (clients: ClientInfo[]): string => {
  const validClients = clients.filter((c) => c.hasDefinition);

  const subCommandEntries = validClients.map((c) => {
    return `    '${c.kebabName}': () => import('./commands/apis/${c.kebabName}.js').then((m) => m.default),`;
  });

  return `import { defineCommand } from 'citty';

export const main = defineCommand({
  meta: {
    name: 'epilot',
    version: '0.1.0',
    description: 'CLI for epilot APIs',
  },
  args: {
    token: { type: 'string', alias: 't', description: 'Bearer token' },
    profile: { type: 'string', description: 'Use a named profile (or EPILOT_PROFILE env)' },
    server: { type: 'string', alias: 's', description: 'Override server base URL' },
    json: { type: 'boolean', description: 'Output raw JSON' },
    verbose: { type: 'boolean', alias: 'v', description: 'Verbose output' },
    interactive: { type: 'boolean', default: true, description: 'Interactive mode' },
    jsonata: { type: 'string', description: 'JSONata expression' },
  },
  subCommands: {
    auth: () => import('./commands/auth.js').then((m) => m.default),
    profile: () => import('./commands/profile.js').then((m) => m.default),
${subCommandEntries.join('\n')}
  },
});
`;
};

const generateDocs = (clients: ClientInfo[]) => {
  const docsDir = resolve(CLI_DIR, 'docs');
  mkdirSync(docsDir, { recursive: true });

  for (const client of clients.filter((c) => c.hasDefinition)) {
    const lines = [
      `# ${client.title}`,
      ``,
      `**API Name:** \`${client.kebabName}\``,
    ];

    if (client.serverUrl) lines.push(`**Base URL:** \`${client.serverUrl}\``);
    if (client.description) lines.push(``, client.description);

    lines.push(``, `## Operations`, ``);

    if (client.operations.length > 0) {
      lines.push(`| Operation | Method | Path | Summary |`);
      lines.push(`| --------- | ------ | ---- | ------- |`);
      for (const op of client.operations) {
        lines.push(`| \`${op.operationId}\` | ${op.method} | \`${op.path}\` | ${op.summary} |`);
      }
    } else {
      lines.push(`No operations found.`);
    }

    lines.push(``, `## Usage`, ``, '```bash');
    if (client.operations.length > 0) {
      const first = client.operations[0];
      lines.push(`epilot ${client.kebabName} ${first.operationId}`);
    } else {
      lines.push(`epilot ${client.kebabName}`);
    }
    lines.push('```', ``);

    writeFileSync(resolve(docsDir, `${client.kebabName}.md`), lines.join('\n'));
  }
};

const main = () => {
  console.log('Discovering clients...');
  const clients = discoverClients();
  const validClients = clients.filter((c) => c.hasDefinition);
  console.log(`Found ${clients.length} clients, ${validClients.length} with definitions`);

  console.log('Copying OpenAPI definitions...');
  copyDefinitions(clients);

  console.log('Generating api-list.ts...');
  mkdirSync(GENERATED_DIR, { recursive: true });
  writeFileSync(resolve(GENERATED_DIR, 'api-list.ts'), generateApiList(clients));

  console.log('Generating per-API command files...');
  mkdirSync(APIS_CMD_DIR, { recursive: true });
  for (const client of validClients) {
    writeFileSync(resolve(APIS_CMD_DIR, `${client.kebabName}.ts`), generateApiCommand(client));
  }

  console.log('Generating index.ts...');
  writeFileSync(resolve(CLI_DIR, 'src', 'index.ts'), generateIndexFile(clients));

  console.log('Generating docs...');
  generateDocs(clients);

  console.log(`\nGenerated:`);
  console.log(`  - ${validClients.length} definition files`);
  console.log(`  - ${validClients.length} API command files`);
  console.log(`  - ${validClients.length} doc files`);
  console.log(`  - 1 api-list.ts`);
  console.log(`  - 1 index.ts`);
  const totalOps = validClients.reduce((sum, c) => sum + c.operations.length, 0);
  console.log(`  - ${totalOps} total operations across all APIs`);
  console.log(`\nAPI names: ${validClients.map((c) => c.apiName).join(', ')}`);
};

main();
