name: Auto Package
on:
  push:
    branches: ["auto/**"]

jobs:
  build:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Commit Changes
        run: |
          git config user.name "Thank God It's Friday"
          git config user.email 'dev@epilot.cloud'
          git add .
          git commit . -m 'Built client files added'
          git push
      - uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}